terminate evr-attr-index if connection to evr-glacier-storage fails

diff --git a/testing/suite/attr-index/run-suite b/testing/suite/attr-index/run-suite
--- a/testing/suite/attr-index/run-suite
+++ b/testing/suite/attr-index/run-suite
@@ -7,6 +7,22 @@ allocate_ports
 write_evr_conf
 trap stop_everarch_servers EXIT
 
+# start evr-attr-index server without evr-glacier-storage running. it
+# should terminate.
+timeout_ret=0
+timeout 10s evr-attr-index || timeout_ret=$?
+echo "timeout status ${timeout_ret}"
+if [[ "${timeout_status}" == "124" ]]
+then
+    echo "evr-attr-index did not terminate with missing evr-glacier-storage" >&2
+    exit 1
+fi
+if [[ "${timeout_ret}" == "0" ]]
+then
+    echo "evr-attr-index ended with return code ${timeout_ret}" >&2
+    exit 1
+fi
+
 start_glacier_storage
 wait_for_glacier_storage
 
