make evr-glacier-storage and evr-attr-index daemons

diff --git a/testing/suite/config b/testing/suite/config
--- a/testing/suite/config
+++ b/testing/suite/config
@@ -11,18 +11,15 @@ evr_wait_timeout=20
 
 glacier_storage_port=2461
 glacier_storage_bucket_dir=storage
-glacier_storage_pid=
 glacier_storage_cert_path="${script_dir}/../tls/glacier-cert.pem"
 glacier_storage_auth_token='ac78ca737213680040b3c6420f04d6ede163e3a15fef022d281af87f31e25179'
 
 secondary_glacier_storage_port=2561
 secondary_glacier_storage_bucket_dir=secondary-storage
-secondary_glacier_storage_pid=
 secondary_glacier_storage_auth_token='ee3e9ad7a89ef1745f54f91689207d27d1b976a2791dca30ce74aef5c251e40f'
 
 attr_index_port=2462
 attr_index_state_dir=attr-index
-attr_index_pid=
 attr_index_cert_path="${script_dir}/../tls/attr-index-cert.pem"
 attr_index_auth_token='7c0c40cb392ceeb42097988f21ed968f3590f25ae3deca8632e4a905cd340cbe'
 
@@ -106,11 +103,15 @@ append_accepted_gpg_keys() {
 }
 
 start_glacier_storage() {
-    rm -rf -- "${glacier_storage_bucket_dir}"
+    rm -rf -- "${glacier_storage_bucket_dir}" evr-glacier-storage.pid evr-glacier-storage.log
     mkdir -- "${glacier_storage_bucket_dir}"
+    if [[ -e evr-glacier-storage.pid ]]
+    then
+        echo "Unable to start evr-glacier-storage. evr-glacier-storage.pid already exists" >&2
+        exit 1
+    fi
     echo "Starting evr-glacier-storage…"
-    evr-glacier-storage &
-    glacier_storage_pid=$!
+    evr-glacier-storage --pid evr-glacier-storage.pid --log evr-glacier-storage.log
 }
 
 wait_for_glacier_storage() {
@@ -118,11 +119,10 @@ wait_for_glacier_storage() {
 }
 
 start_secondary_glacier_storage() {
-    rm -rf -- "${secondary_glacier_storage_bucket_dir}"
+    rm -rf -- "${secondary_glacier_storage_bucket_dir}" evr-glacier-storage-secondary.pid evr-glacier-storage-secondary.log
     mkdir -- "${secondary_glacier_storage_bucket_dir}"
     echo "Starting secondary evr-glacier-storage…"
-    evr-glacier-storage --port "${secondary_glacier_storage_port}" --auth-token "${secondary_glacier_storage_auth_token}" --bucket-dir "${secondary_glacier_storage_bucket_dir}" &
-    secondary_glacier_storage_pid=$!
+    evr-glacier-storage --pid evr-glacier-storage-secondary.pid --log evr-glacier-storage-secondary.log --port "${secondary_glacier_storage_port}" --auth-token "${secondary_glacier_storage_auth_token}" --bucket-dir "${secondary_glacier_storage_bucket_dir}"
 }
 
 wait_for_secondary_glacier_storage() {
@@ -130,20 +130,14 @@ wait_for_secondary_glacier_storage() {
 }
 
 start_attr_index() {
-    rm -rf -- "${attr_index_state_dir}"
+    rm -rf -- "${attr_index_state_dir}" evr-attr-index.pid evr-attr-index.log
     mkdir -- "${attr_index_state_dir}"
     echo "Starting evr-attr-index…"
-    evr-attr-index &
-    attr_index_pid=$!
+    evr-attr-index --pid evr-attr-index.pid --log evr-attr-index.log
 }
 
 stop_attr_index() {
-    if [[ -n "${attr_index_pid}" ]]
-    then
-        kill -s sigint "${attr_index_pid}"
-        wait "${attr_index_pid}" || true
-        attr_index_pid=
-    fi
+    stop_via_pid_file 'evr-attr-index.pid'
 }
 
 wait_for_attr_index() {
@@ -222,7 +216,6 @@ wait_for_content() {
     sleep 0.1
     while true
     do
-        echo ">>> ${fn}"
         if [[ -e "${fn}" ]]
         then
             local content=`cat "${fn}"`
@@ -256,26 +249,29 @@ ensure_port_available() {
 stop_everarch_servers() {
     umount_evr_fs
     stop_attr_index
-    if [[ -n "${glacier_storage_pid}" ]]
+    stop_via_pid_file "evr-glacier-storage.pid"
+    # test lock to make sure evr-glacier-storage has released lock
+    if [[ -e "${glacier_storage_bucket_dir}/lock" ]]
     then
-        kill -s sigint "${glacier_storage_pid}"
-        wait "${glacier_storage_pid}" || true
-        glacier_storage_pid=
-        # test lock to make sure evr-glacier-storage has released lock
-        if [[ -e "${glacier_storage_bucket_dir}/lock" ]]
-        then
-            flock -n "${glacier_storage_bucket_dir}/lock" true
-        fi
+        flock -n "${glacier_storage_bucket_dir}/lock" true
     fi
-    if [[ -n "${secondary_glacier_storage_pid}" ]]
+    stop_via_pid_file "evr-glacier-storage-secondary.pid"
+    # test lock to make sure evr-glacier-storage has released lock
+    if [[ -e "${secondary_glacier_storage_bucket_dir}/lock" ]]
     then
-        kill -s sigint "${secondary_glacier_storage_pid}"
-        wait "${secondary_glacier_storage_pid}" || true
-        secondary_glacier_storage_pid=
-        # test lock to make sure evr-glacier-storage has released lock
-        if [[ -e "${secondary_glacier_storage_bucket_dir}/lock" ]]
-        then
-            flock -n "${secondary_glacier_storage_bucket_dir}/lock" true
-        fi
+        flock -n "${secondary_glacier_storage_bucket_dir}/lock" true
     fi
+}
+
+stop_via_pid_file(){
+  local pid_file="$1"
+  if [[ -e "${pid_file}" ]]
+  then
+    local pid=`cat "${pid_file}"`
+    local fn=`basename "${pid_file}"`
+    echo "Stopping ${pid} via ${fn}…"
+    kill -v -s sigint "${pid}"
+    tail --pid="${pid}" -f /dev/null || true
+    rm "${pid_file}"
+  fi
 }
